---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: pre-defined-secret
  namespace: arc-runners
spec:
  encryptedData:
    github_token: AgBXqRLYAeFqVtss5nrCLz5/SvXK1OWBkEdxhtXghn/4Et+TBRy44rdwG19mj1EvnfIpFt+ysUKK1LNN1qTQ0wXySpkXgZgzRNqURVsewPb5Yb23NMZCjITLQoj9pTDyUOymDV6LtHMhpAFvkXXv4d3EBivGCAzScUlzvKXKfSB5IGqiVYOBSq0lXnCKUic7xJAJVHhbR3UJeQvvmL5DrQanqwN1R/GQNPRT27O8+8K+P7u6XD9f8b0OWRkkESA6m18gkMFGkcfhn8k3dSX7K0vrjgYPq6LkZfUMT0PW3le/YSdCK4oWmOSCWOZW/D1qHYgyzEiN+Eyd2dpGdfogWnjre6NEm1M34A+0wR+izzwICcxCeUaelQAT71O2A+2vlIGOiaOhBqow5pHw1JgXeFbcYtN3244x7WBu+aOI2H+e/kVZMcjHQoHz3+FM7d6YmJNExpnI/q19P57tjdt+3fzmP6HXqJyitfTbsrVUN7IuXhiod1TYmuxQYIxLplg2eyDz9mHK+mzpOjpDIurlFfSQkrDe4IRfaaYuAkxMp8oHgsTj03ZIAJ1fhXrhEzkBrwEMeP6RR3RXzUhwAClKh9O+1vdspJQiezHEf1QDJa+Qle28ab8hA2BYUOKHLE8oS+U4wEG1ci40VEz5HQgB6i/aJJBQEb8u5RmaGWlNocjVWgH0t/UKUJw///r0Vp1N8bjCHtHclS8B8NC3ammhR+h3GrJzfXWdeVabqKEd1gM6P60GwS7c0rggq1iBRfWceoWqYxqOy4dB93+x0/QnFkSW9uqnMuw6Tv/+Ar1GyMoklLgjx55DjfSHKdcfMjM=
  template:
    metadata:
      creationTimestamp: null
      name: pre-defined-secret
      namespace: arc-runners
    type: Opaque
