---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: pre-defined-secret
  namespace: arc-runners
spec:
  encryptedData:
    github_token: AgDSJ4gKtzsaNXbDbzmAwOdAm3TJSKOU/peWUIIC2O5B30dxjqOEDzDvxXAaGoGm76hTZ/8y1XLIwkxo8Tg1eu6YfWfzxB7bz8bSSLqQqs+u8+qOc06GpeadFfas69hzZgaCMkmi/CCYbc2Kv6bMynvOnetpWAQ9/7AfL15mJO0B6KHAnav55fqluBy394U+MgRVlNM7pOY/b7hHV66FwNoBMiEEaoI1eFwgWQhu7PmTSpoSOA+/Z+PdEaAkCLtlu+la24H98KzYc28Z0F/4jMTe3gIcxvHUlYLrc63joY/2kPp4BvktBHVfxRGZckbLU8OuXqNQF4veNzuDI4TeZWPuhvNXIK4KHa+qmdtY+pS3C79QuwJ8yhKLrzKT5HQgsZzwNE+6l78GcvAbE/q/LZkoWu4OXnkgJAlxgKnNrCIRw9apaoLs2UY75c4p4SWHr7xpLVVevG+q7o00ZPqMjxSWRHTh3wahBKV8urQtaNpk2tpiHEX4GhthzfDj5ZbLZa3kR4vjuE1oZ03J4syqOTRzXX+3p+/RlznW5sfFApy7330zaaS0t+0r6RP+5BwmPqXhJKeEE5mkZ+z8r1oufCC+Jqx3uh6+VQFkJVOYJbSnXToT2aegjeh7bJwww4oOCxlKrOdRsMc70Vp/NcQB9SZxQEteEfpQQ87Hx4s2bnuJ2foCPShrgh//EOTco+s7QDkwkpeZbRK1f72XDLqgEwcNc0k9RIo3sE6JFWvDjxo1f0tAWICJdmZJ
  template:
    metadata:
      creationTimestamp: null
      name: pre-defined-secret
      namespace: arc-runners
    type: Opaque
