apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: arc-runner-set-eso
  namespace: arc-debug
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp 
    kind: ClusterSecretStore      
  target:
    name: arc-runner-set-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: arc-runner-set-secret
