apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: arc-runners-admin-binding
subjects:
- kind: ServiceAccount
  name: default  # ServiceAccount utilisé
  namespace: arc-debug  # Namespace de votre ServiceAccount
roleRef:
  kind: ClusterRole
  name: cluster-admin  # Rôle intégré avec accès complet
  apiGroup: rbac.authorization.k8s.io
