apiVersion: v1
kind: Pod
metadata:
  name: kubectl-helper
  namespace: arc-debug
spec:
  containers:
    - name: kubectl
      image: bitnami/kubectl:1.28.5
      command: [ "sleep", "3600" ]
      stdin: true
      tty: true
      securityContext:
        runAsUser: 0   
        runAsGroup: 0  
    - name: curl
      image: curlimage/curl:8.11.1
      command: [ "sleep", "infinity" ]
      stdin: true
      tty: true
      securityContext:
        runAsUser: 0   
        runAsGroup: 0  
  imagePullSecrets:
    - name: arc-runner-set-docker-secret
