apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: list-namespaces-binding
subjects:
  - kind: ServiceAccount
    name: dev-apig-gha-rs-no-permission
    namespace: cmdo-arc-runners-apig
roleRef:
  kind: ClusterRole
  name: list-namespaces
  apiGroup: rbac.authorization.k8s.io