---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: pre-defined-secret
  namespace: arc-runners
spec:
  encryptedData:
    .dockerconfigjson: AgC4oWin7rqtXZ9YOYo2TZXpKTgjpld6PLOSXoV7Lp0U6dJ5dewg/1VlGQnkrcE5RCj9E9CFLAyxnJQfzJ7wiNncJPyanCtTi2PXtSjEZTRLUXLTzA42agOnNyKcdOQl8ti0qI7DmcWieHh9PHgcEAqOymRwWhFSSRVnTc9oiCjke8bSXvdr33kx8JGeSGcJYszPfSDoX05Fl+Z6LuZN39sZJWqy+udJWp557gu5j5ccEWvRlCwEists4cmW4bO+Q2S0aAuWGrUoGfKbcOLWP3PoYhqfJwJ5CKFPOZkYqJWA9HjqIqhYfPkOibuZPE8jSLv7RC0z+4fKiTgNulhpDne+7ZLvC9gaYdAa9yv7tav/mTMs1Kfa3tjfdsFESES01lGAZtafvufBku7D+OCpCQPgaX56EMXr2yttZKJPYMnzDIc/5U99un7ybJa2zlYexTeYjhf3WCRXMDAejykXFhP39NrSyuTnzOQfBgmX+8jQ0nPV5XXpU5umeb8UUrtV8IUjoGMVf/2TXkDl/Zp+3E29HAus00zG0cy0Qu0If2fXx2BaIUPiF2X0fsf31JdT/KDCPtM4V3vzaL0YkfBAoq80bk9Vum6oCe79/OgBpU6gvrUCX9HSILwrX204SoTSfYgH3bR+qTB1j/LxTBF0Js/dlL8EmNO98qHO9t9g6Gnmf0qRll5HItEvJ3Wuv5jBUJwlVoanc41idxvDS+6NdxuvzXrCLjYTO3MPPRwGoIgOY5swN8iURVpOA0VSWMon1y0o5TQvM34CWBPtwipFcGAZ9YNx1mQ8bC0GAdijVAMr4k0wrKjvs52T95BS1Ng/u3g5ktoWM88GQs2SRDhUbfDzJzVXS158mDc9O/0bx8sVB0iGft6dnOfVgJv6bdke6YoNDqWK+7p8eoe/dSu9ObmXlrX+
    github_token: AgCyLvCF3SaLyigfLxoIGuMmaHOJ1FCKvpKjNFkxLtTKnzWNX7QsUOKzBIgrx/SCjVfXGk4ebpJa1dmhzF73APoREOlGhvdVnasK5DwNejsypVb/BTXx7z1cwbWQrkH5NTIvWwih+uMWewjHXy18W+vDthml0PXZRmI+fnfp+Y1/3R6oQBkofrq+2oo9oRLXmrt3HFcNsdleM9ka3+Ku4jNlT+qqSiT6zGFY23HwBg2A3YBursy4GZYfd81Ed05afMTkB9SQjKC6F7/Ekgpu1dtomqWI/bM2CTRkp8V6ODyl5ygOAcYPA/ymcOMF6oY8Ck3i8TdDR8+0r27CtwU/DW7vsUrForAp8s6CBEmR918aQQZ0af5My8z52yZx0szqYBylHRh80RABo3PJAMrnDBk0PYkHhYuD9hFuqcVjJSrlYYKflndmuCXh04ZQQf+cS/IA96jeXcobizyTfoAe3uva8V94wF4hGlkeIjXOoLcmaL9oVWUdimlvn56fiSH51D6al3gp7ftFYLgjYynaBXj2rMmehg9oyOa6PuLr9VwbRbdzZMNUeiLLMPlnmnSLdyLxSJli9l15CbgJISzTV2LR/jFht2EEFbHeJIq0FMGDv7kBhEGte4eZ/vEvG1JEg6eE6rXFDxfrmdRe1g6N5GBA2rVUiWZwddSwvvFNFXieNkjjFgpKyBQEta8hX03pX7x3txZnJ7bfxXdt/EsslYjw9HOukWO80vDDypBUuBm6iZi2vyC3kgto
  template:
    metadata:
      creationTimestamp: null
      name: pre-defined-secret
      namespace: arc-runners
    type: kubernetes.io/dockerconfigjson
