---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: pre-defined-secret
  namespace: arc-runners
spec:
  encryptedData:
    .dockerconfigjson: AgCEIorc01q2AxJjkBqBIpKWe3NYO75Y+1vXZyPQrCdVW0HM3uBAIu+XeV6mG/kSPd7300WXyRlc0qPxtXgfl9caU5DPUbcaiJmAKPjv42+K8Qv7WnVeLKcizdBSRzqAo+RMrOOoMzVRb+bHgvk6fs5XkHOsF+fTq2T/tDsfD2GJ60d2P/HBmmbRYeEGFcXYxJjsSKfcujgQ0HqIuBy7LTfPrGnS+QreDTZTzI6Q1HFbN/s0lvkiuIFWvwr0lMm9Hd3Z96LLnbo6qfVzCgTFYIuZzrTFB+/JRB6P+4Tmfh8r8TN8Sl4Mf19Vx1SR0IX4sGwrRzL3xDgTCpnUAIoipQLZaMhKgIRVIhBy6APzeXnCHS5zUqJiyzts6gEWiM/uk9aq1tUsauVe+n3VRDNuf6Hd+JXwIbhLfvH0nRwLaok6dQg9bv0Mv/M5SpAQ0WLTyrw4kwZmghWp2K0cSjeD37J8419mP0CuCkAaJuKAA9xJvGAQrz8E+8roNbt9fFjTraaKHKb22JhrYU21ZZFClN8ejw8YCQE/D7O5hmVreQHDMcQ7wLTsITZUWUdOT0+cPt/AxkNuC4tejapX0ILrFPlWK/BMTIvVi/cexzYWhobIjwA8n2iMqvAvJQGf3hDsfsTCocvP4rdX2LNj1GD5qapn7o9eqt3/SloFm77JxPDkJS0gGu4kmKr6T1qe7mfMIvv6TB/ZyvuLzsCpi1B+wH7C2aJ64uVR/RapSPi6ni9mPM2AzSC4TzsBeA9ymAjpPyumGseBAhzQUe+hmyuePDpZKDfbn56TUigj1LvEhrxPlobE0LOW60By4338OsTjlCaKA6dCXtbp/VM=
    github_token: AgALoJVqy3Qexq7nj6JzgPd6GbEr9AxGD7QBDAvqeBe6Q+X4Jp76YnsD/U5vVGEkrcE+rHpZq2BKGtEx2cPLWPI/nOIcQKJz+AiZH+eQYS9TXuguzJeyd/W51vzadsyrWxfJDGshNOPzZ/ldr2pn5GdjIVC4nNzO2uq3mj/iivLZXA+TUeFgr+dthGqeK/C5kVkrv3LvzZnkJtc5j5G1rO5VWLX5wC1+iaU0vDTQxbf4wpb6RMNMvNh3RcKaPgv51JaJ/CXYfnhsXG1jMNWhFq98zYUCL+ZQo8g0KpQ80jgVSn+6Pzy7BBYqc7hnffqTOsOcZcW3Ti3n510QDb1sNqsYtOr7TH3uUgSbw+311VdSBHT9uUVOQ5ih8Q0GNg9pCIekWdVfomRsy7W5T0f7AdZOPwr0EKOclWN9w73yDI5cEU9HrBn2HnAjP8xCqNtulKY3WiUtfBh44Td6p4Anz1689q4VUKbCp3zApGWX9gTS3ifjw21pHqrQJCGlxpgvzSLVP1mORIWP3ari+q6VaRKj2z5UcfgPuvXvvq3+DSQj45JmWm9esL09g8/0THe+ou6HP6W2GYX/+EBDGrQeRvoKOrf9C09akfUpfXmrf70OF/WgyWCe6t9h7/xznFh2AjCmFXYZiVXbq8oOoHuhZhY+i7QbFlGF2ueIUERAwgtbL2VjHc0JoOzXl7m2gRKSbrbd4Cb6oQ1rzqXvk7RqMBoZtzplNgGqSe7SJ4rL1xtAw0rwl96igJpD
  template:
    metadata:
      creationTimestamp: null
      name: pre-defined-secret
      namespace: arc-runners
    type: kubernetes.io/dockerconfigjson
