---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: pre-defined-secret
  namespace: arc-runners
spec:
  encryptedData:
    github_token: AgBb3gJMHG6/Omzti4wKtnfp6FsXfx9Mwp/APppLMnPSwOR+75WIbms48D+IORGOgFgFP3NCgc/idC547MrshN0VWUYjTluNxM7QbwXmpuwGMrK2uEakY32xuhr6QAOn0qNoBHDZjxUVPCoJ9MeEYmpUkA5TTBlDnix/IFNNt/MebP7cvI7BMuSlknyZ6+cX5f9QFgpdh1DGPxLJ4U9R/KsiHb8J5CRRDF3tQL+hWDJ/iTFjl4TK0gUeCNkbBJIzo8AeWYxEzuaOnHE+5XhthbDWN2yhpq6yfKZqszEHbRw/h/2ykvbIPBAHv+PChf5RXxd4k3EcJ8E5GUGpaSmPLOS0n6t/5MQ4haYMIerkH6HlYphAW7uU0WHM6XP38fFAn9MDO4ZAljhwxkXFJQEb873zrKe3azqwnzbX73GjusYQKVq5hQuLpudzf0ttPrX90azyupmaNUciaX56uuoMF28SBE7+eszBBYtNNTOjMeCj8C/iSeabTksyt//9n5lAHhUkiZ8nCRDXWSm38XwbuIA2sC6n8n+MLpZbt68ETQWKfIu7weiXp0MfnjLJbnyMadx4A2m6WnQ+qf08wXSpDzVk89r89jkW4jPQARoJ5RrIzaTPB8TAp7VbD499C149sAvSNVAYgLSzjOx8TGd8gg7klgz7D0ohMvNWAKHAsRFoLj9B0xcNpuAIKZXa4G+nDAMFYHYcJVUROaH1s7S8Zj9fRewnP41AnziydShfATK/lAh5lu+xmyoP
  template:
    metadata:
      creationTimestamp: null
      name: pre-defined-secret
      namespace: arc-runners
    type: Opaque
