apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: arc-docker-eso
  namespace: cmdo-arc-systems
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp 
    kind: ClusterSecretStore      
  target:
    name: arc-docker-secret
    template:
      type: kubernetes.io/dockerconfigjson
    creationPolicy: Owner
  data:
    - secretKey: .dockerconfigjson
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: Auto
        key: arc-docker-secret
        metadataPolicy: None
