---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: pre-defined-secret
  namespace: arc-systems
spec:
  encryptedData:
    .dockerconfigjson: AgCYycIfH9boue8ckcMUx7KV7wcGShUQkiqu+WOmxsGvpv6qoC4TWsywIPFBvXvR2q1ZbRmvhGHBIbmkgiciybP/YsUiK7uE586oRq4pSiGfwhUsI4kySXK2aM1xXHqnY9zR71NnniwdW0ZHGAL/b8PZ7FjZW+wvDwIoerVEitjTULvwWKyL0gskCwy/kk39+RdwYsxstGuBn5x+4BEjHNQEONhCgvXUiMxWLhdLsqKPGE7eXa+0IKDNTlNXYTkevkj48QQLsfrNAnOFDxkp8PJ9hCCY1J6tsNjN6BjK1srmj+quT+RCEGJECOanb7UZ+3xRNfOxewcm3K1W2av1BxWEYZZevsbIpKDmoNuwFYR3w1+KdhhEAo+Rd6lLLwDQ2Ea6BnYAfy+qWjwRV/KgRN3jR3MQhh1eyYHhMBjn41HVRDfjf2M4DlXHnOd4JNH3KnoaOY3PsXoq9gQ7fJKF0SUNGxzEY4yXjwt44VrAEERJnyuWpU34qBOIwkQzWRE2nYyGT/57cxAYFlNbi7iJs3Uv5ulxUGgt3yzWmM3VXkTAZpBSEqJ/aj4XFkGhELu7rSg4nMrJk7iTy5l7RjcPgtif6L4wz/6IaSLozNPAaeiKVI3YIgadP5PInKfTGewMQ938dcwc3u8DtFGKBldt7sIQ8S4rjoitV319hHbIo4cmVq6dtMoWWVzAcpSKYx6wXhxxcmRwsd3vwhSeTOu0JxR+el4iyiCoRWbgVclDg72RTwBfhxAWsQsbkDUYPt2Muga68T88uSsw93itURVxdsB716dWqwnXZyTfD7lIrra3Plx/P/+n6a2VepWYeVoIcNE56Gt/hgdha5CbrIkHW4MhPopNBb3BteLyTr8gOcgrhdsGDRDOEfew8IccX1DmZbcjH69sKCamhiVbzG3HMIELhG2s
  template:
    metadata:
      creationTimestamp: null
      name: pre-defined-secret
      namespace: arc-systems
    type: kubernetes.io/dockerconfigjson
